services:
  litterbox:
    image: python:3.9
    volumes:
      - .:/app
      - app_data:/app/data
      - ./Config:/app/config
    working_dir: /app
    command: ["sh", "-c", "pip install -r requirements.txt && python litterbox.py"]
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  app_data:
